Don't include facts with geometry issues
digital-land/digital-land-python pull request #306
Opened 2024-12-09 10:17 UTC by cjohns-scottlogic

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Don't include facts with geometry issues.

## Related Tickets & Documents

- Ticket Link
- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [X] Yes
- [ ] No, and this is why:
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

## [optional] Are there any dependencies on other PRs or Work?

2024-12-09 11:24 UTC, eveleighoj requested changes
This doesn't look like the best place to be doing this. It's duck taping a solution on later but not figuring out why t he issue has been raised but the value not removed.

2024-12-09 15:31 UTC, cjohns-scottlogic commented
> This doesn't look like the best place to be doing this. It's duck taping a solution on later but not figuring out why t he issue has been raised but the value not removed.

Yeah, good spot. I've moved it to the harmonise phase. I've left the pivot test (without the exclude fields elements).

2024-12-09 17:01 UTC, alexglasertpx approved these changes

2024-12-10 09:50 UTC, eveleighoj approved these changes

2024-12-10 10:12 UTC, merged